---
title: "Draft R Markdown document"
author: "Your Name"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(vroom)
source(here("R/functions.R"))
```

## importing raw data

```{r}
user_1_info_file <- here("data-raw/mmash/user_1/user_info.csv")
user_1_info_data <- vroom(user_1_info_file)
```


```{r}
user_1_info_data <- vroom(user_1_info_file,
                          col_select = -1,
                          col_types = cols(
  ...1 = col_double(),
  Gender = col_character(),
  Weight = col_double(),
  Height = col_double(),
  Age = col_double(),
  .delim = ","
)
)
```

```{r}
user_1_info_data <- vroom(
    user_1_info_file,
    col_select = -1,
    .name_repair = snakecase::to_snake_case)
```


```{r}
user_1_info_data <- vroom(user_1_info_file,
                          col_select = -1,
                          col_types = cols(
  col_skip(),
  gender = col_character(),
  weight = col_double(),
  height = col_double(),
  age = col_double(),
  .delim = ","
),
.name_repair = snakecase::to_snake_case

)

```


## importing saliva data

```{r}
user_1_saliva_file <- here("data-raw/mmash/user_1/saliva.csv")
user_1_saliva_data_prep <- vroom(
    user_1_saliva_file,
    col_select = -1,
    .name_repair = snakecase::to_snake_case
)

spec(user_1_saliva_data_prep)

user_1_saliva_data <- vroom(
    user_1_saliva_file,
    col_select = -1,
    col_types = cols(
        samples = col_character(),
        cortisol_norm = col_double(),
        melatonin_norm = col_double()  
    ), 
    .name_repair = snakecase::to_snake_case
)

```

## importing larger dataset

```{r}
user_1_rr_file <- here("data-raw/mmash/user_1/RR.csv")
user_1_rr_data_prep <- vroom(
    user_1_rr_file,
    n_max = 100,
    col_select = -1,
    .name_repair = snakecase::to_snake_case
)

spec(user_1_rr_data_prep)

user_1_rr_data <- vroom(
    user_1_rr_file,
    col_select = -1,
    col_types = cols(
  col_skip(),
  ibi_s = col_double(),
  day = col_double(),
  time = col_time(format = "")
),
.name_repair = snakecase::to_snake_case
)
```



```{r}
name <- function(argument1, arugment2) {
    output <- ...code...
    return(output)
}
```

## Making a function

```{r}
#' Add two numbers together.
#'
#' @param num1 A number
#' @param num2 A number
#'
#' @return The sum of two numbers
#' 
add_numbers <- function(num1, num2){
    added <- num1 + num2
    return(added)
}
```


```{r}

```

```{r}
import_user_info(here("data-raw/mmash/user_1/user_info.csv"))

import_user_info(here("data-raw/mmash/user_2/user_info.csv"))


```


## Exercise for importing the saliva data as a function. 

```{r}
#' Import the MMASH saliva dataset.
#'
#' @param file_path Path to the user saliva data file.
#'
#' @return Outputs a data frame/tibble.
#'
import_saliva <- function(file_path) {
    saliva_data <- vroom(
        file_path,
        col_select = -1,
        col_types = cols(
            samples = col_character(),
            cortisol_norm = col_double(),
            melatonin_norm = col_double(),
            .delim = ","
        ),
        .name_repair = snakecase::to_snake_case
    )
    return(saliva_data)
}

# Test that this works
# import_saliva(here("data-raw/mmash/user_1/saliva.csv"))
```









