---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
library(tidyverse)
library(here)
library(fs)
source(here("R/functions.R"))
```

## Importing new data

```{r}
#| eval: false

here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```


## Exercise: reading other files

```{r}
#| eval: false

here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case
  )

here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )

here("data-raw/nurses-stress/stress/6B/6B_1587569373/EDA.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case
  )

here("data-raw/nurses-stress/stress/6B/6B_1587569373/EDA.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

```{r}
#' Add two numbers together.
#'
#' @param num1 A number here.
#' @param num2 A number here.
#'
#' @returns Returns the sum of two numbers
#'
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}
```

```{r}
#| eval: false

#' Read in one nurses' stress data file.
#'
#' @param file_path A path to a data file
#'
#' @returns outputs a data frame / tibble
read <- function(file_path) {
  data <- file_path |>
    read_csv(
      show_col_types = FALSE,
      name_repair = to_snake_case,
      n_max = 100
    )
  return(data)
}
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read()
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()
```

```{r}
#| output: false


here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()
```


## Using map

```{r}
hr_files <- here("data-raw/nurses-stress/") |>
  dir_ls(regexp = "HR.csv.gz", recurse = TRUE)

hr_files


hr_data <- hr_files |>
  map(read) |> # NO BRACKETS!
  list_rbind(names_to = "file_path_id")

hr_data
```


## Loading all
```{r}
df <- read_all("HR.csv.gz")
```

## inspecting the data
```{r}
hr_data <- read_all("HR.csv.gz")

survey_data <- here("data-raw/nurses-stress/survey-results.csv.gz") |> 
  read()

hr_data
survey_data
```

```{r}
hr_data |> 
  mutate(
    id = str_extract(
      file_path_id,
      pattern = "/stress/[:alnum:]{2}/"
    ) |> 
      str_remove("/stress/") |> 
      str_remove("/"),
    .before = file_path_id
  ) |> 
  select(-file_path_id)
```

## Working with across

```{r}
hr_data <- read_all("HR.csv.gz") |> 
  get_participant_id()

hr_data
```


```{r}
hr_data |> 
  summarise(across(where(is.numeric), list(mean = mean, 
                            median = median,
                            sd = sd)))
```

## Working with dates


```{r}
hr_data |> 
  mutate(datetime = round_date(collection_datetime, 
                               unit = "minute"),
         .before = "collection_datetime")
```

## Summarising by groups

```{r}
hr_data |> 
  mutate(
    collection_datetime = round_date(
      collection_datetime,
      unit = "minute"
    )
  ) |> 
  summarise(
    across(
      where(is.numeric),
      list(mean = mean, sd = sd, median = median)
    ), .by = c(id, collection_datetime)
  )
```

## Pivoting longer

```{r}
survey_data <- here("data-raw/nurses-stress/survey-results.csv.gz") |>
  read()
survey_data
```


```{r}
survey_tidy <- survey_data |>
  mutate(
    date = mdy(date),
    start_datetime = as_datetime(paste(date, start_time)),
    end_datetime = as_datetime(paste(date, end_time)),
    datetime_id = start_datetime,
    .before = start_time
  ) |>
  select(-c(date, start_time, end_time, duration))
```

```{r}
survey_tidy |> 
  select(id, datetime_id, start_datetime, end_datetime) |> 
  pivot_longer(c(start_datetime, end_datetime), names_to = NULL, values_to = "collection_datetime") |> 
  group_by(pick(-collection_datetime)) |> 
  complete(collection_datetime = seq(min(collection_datetime),
                                     max(collection_datetime),
                                     by = 60)) |> 
  ungroup()

```

